import type { EnvironmentProfile } from "../types/meaning";

export const SEEDED_ENVIRONMENTS: EnvironmentProfile[] = [
  {
    id: "traditional_religious",
    name: "Traditional Religious",
    constraintField: "Covenantal order under transcendent authority.",
    atmosphericTone: "Solemn, accountable, and reverent.",
    actionArena: "Ritual, teaching, discipline, and public witness.",
    continuityStorage: ["liturgy", "canon", "rule of life"],
    transmissionMechanism: ["catechesis", "mentorship", "institutional memory"],
    auctoritasGradient: ["elder", "teacher", "office", "text"],
    maintenanceLoop: ["confession", "correction", "communal practice"],
    institutions: ["parish", "household", "order"],
    carriers: ["ritual", "office", "vow"],
    obligations: ["obedience", "fidelity", "amendment"],
    consequences: ["blessing", "discipline", "exclusion"],
  },
  {
    id: "kings_court",
    name: "King's Court / Formal Hierarchy",
    constraintField: "Ranked order with explicit duty and public consequence.",
    atmosphericTone: "Ceremonial, strategic, and restrained.",
    actionArena: "Petition, decree, oath, and adjudication.",
    continuityStorage: ["archives", "precedent", "title"],
    transmissionMechanism: ["court schooling", "ritual protocol"],
    auctoritasGradient: ["sovereign", "magistrate", "steward", "subject"],
    maintenanceLoop: ["tribute", "inspection", "sanction"],
    institutions: ["court", "chancery", "crown"],
    carriers: ["office", "rank", "seal"],
    obligations: ["loyalty", "duty", "tribute"],
    consequences: ["promotion", "penalty", "disgrace"],
  },
  {
    id: "rebel_insurgent",
    name: "Rebel / Insurgent",
    constraintField: "Survival under pressure with contested legitimacy.",
    atmosphericTone: "Urgent, distrustful, and sacrificial.",
    actionArena: "Cell coordination, risk-sharing, and signal discipline.",
    continuityStorage: ["oral code", "field lore", "martyr memory"],
    transmissionMechanism: ["apprenticeship", "repeated drills"],
    auctoritasGradient: ["veteran", "cell lead", "runner"],
    maintenanceLoop: ["proof of loyalty", "mutual aid", "after-action review"],
    institutions: ["cells", "safe houses"],
    carriers: ["risk", "oath", "shared loss"],
    obligations: ["silence", "steadfastness", "defense of comrades"],
    consequences: ["exposure", "expulsion", "retaliation"],
  },
  {
    id: "legal_civic",
    name: "Legal / Civic",
    constraintField: "Codified obligations and enforceable process.",
    atmosphericTone: "Measured, procedural, and evidentiary.",
    actionArena: "Hearing, filing, adjudication, and compliance.",
    continuityStorage: ["statute", "case law", "record"],
    transmissionMechanism: ["training", "licensed practice"],
    auctoritasGradient: ["constitution", "bench", "bar", "citizen"],
    maintenanceLoop: ["appeal", "oversight", "public review"],
    institutions: ["court", "agency", "council"],
    carriers: ["evidence", "procedure", "jurisdiction"],
    obligations: ["duty of care", "compliance", "due process"],
    consequences: ["relief", "liability", "sanction"],
  },
  {
    id: "classical_literary",
    name: "Classical / Literary",
    constraintField: "Memory-bearing language aimed at durable form.",
    atmosphericTone: "Composed, elevated, and patterned.",
    actionArena: "Poetry, lament, exhortation, and moral argument.",
    continuityStorage: ["canon", "commentary", "recitation"],
    transmissionMechanism: ["study", "imitation", "public reading"],
    auctoritasGradient: ["author", "tradition", "reader"],
    maintenanceLoop: ["interpretation", "revision", "teaching"],
    institutions: ["academy", "salon", "library"],
    carriers: ["metaphor", "form", "allusion"],
    obligations: ["precision", "memory", "fitting speech"],
    consequences: ["endurance", "misreading", "trivialization"],
  },
  {
    id: "plain_modern",
    name: "Plain Modern",
    constraintField: "Direct speech under low shared ritual.",
    atmosphericTone: "Clear, personal, and practical.",
    actionArena: "Conversation, agreements, and boundary setting.",
    continuityStorage: ["messages", "documents", "habit"],
    transmissionMechanism: ["peer imitation", "media language"],
    auctoritasGradient: ["expert", "peer", "self"],
    maintenanceLoop: ["feedback", "revision", "repair"],
    institutions: ["workplace", "household", "school"],
    carriers: ["clarity", "consistency", "follow-through"],
    obligations: ["truthfulness", "responsibility", "care"],
    consequences: ["trust", "confusion", "drift"],
  },
  {
    id: "modern_corporate",
    name: "Modern Corporate",
    constraintField: "Coordinated delivery under metrics and role boundaries.",
    atmosphericTone: "Strategic, compressed, and reputational.",
    actionArena: "Planning, execution, review, and reporting.",
    continuityStorage: ["playbooks", "dashboards", "policy docs"],
    transmissionMechanism: ["managerial cascade", "onboarding"],
    auctoritasGradient: ["executive", "manager", "IC"],
    maintenanceLoop: ["KPIs", "retros", "performance cycles"],
    institutions: ["teams", "program office", "leadership"],
    carriers: ["ownership", "accountability", "service levels"],
    obligations: ["delivery", "alignment", "risk control"],
    consequences: ["promotion", "reorg", "termination"],
  },
];

export const getEnvironmentById = (id: string) => SEEDED_ENVIRONMENTS.find((env) => env.id === id);
