import type { NarrowFixture } from "./narrowRuntime.ts";

export const PROVING_FIXTURES: NarrowFixture[] = [
  {
    fixture_id: "fx_wq_001_due_process_meaning",
    raw_input: "what does due process mean",
    normalized_input: "what does due process mean",
    governing_term: "due process",
    target_type: "wrapper_query",
    seed_class: "legal_civic",
    expected: {
      route: "READ",
      phrase_mode_fired: true,
      lineage_rendered: true,
      carrier_rendered: false,
      card_state: "B",
      canonical_events_baseline: ["lookup_submitted", "card_rendered"],
    },
  },
  {
    fixture_id: "fx_wq_002_missing_target_clarify",
    raw_input: "what does this mean here",
    normalized_input: "what does this mean here",
    governing_term: null,
    target_type: "wrapper_query",
    seed_class: "unsupported_unbounded_wrapper",
    expected: {
      route: "READ",
      phrase_mode_fired: false,
      lineage_rendered: false,
      carrier_rendered: false,
      card_state: null,
      canonical_events_baseline: ["lookup_submitted", "route_clarification_shown"],
    },
  },
  {
    fixture_id: "fx_pf_001_opaque_idiom_kick_bucket",
    raw_input: "what does kick the bucket mean",
    normalized_input: "what does kick the bucket mean",
    governing_term: "kick the bucket",
    target_type: "wrapper_query",
    seed_class: "opaque_idiom",
    expected: {
      route: "READ",
      phrase_mode_fired: true,
      lineage_rendered: false,
      carrier_rendered: false,
      card_state: "B",
      canonical_events_baseline: ["lookup_submitted", "card_rendered"],
    },
  },
  {
    fixture_id: "fx_pf_002_religious_scriptural_agape",
    raw_input: "what does agape mean",
    normalized_input: "what does agape mean",
    governing_term: "agape",
    target_type: "wrapper_query",
    seed_class: "religious_scriptural",
    expected: {
      route: "READ",
      phrase_mode_fired: true,
      lineage_rendered: true,
      carrier_rendered: true,
      card_state: "B",
      canonical_events_baseline: ["lookup_submitted", "card_rendered"],
    },
  },
  {
    fixture_id: "fx_pf_003_historical_resonant_republic",
    raw_input: "what does republic mean",
    normalized_input: "what does republic mean",
    governing_term: "republic",
    target_type: "wrapper_query",
    seed_class: "historically_resonant",
    expected: {
      route: "READ",
      phrase_mode_fired: true,
      lineage_rendered: true,
      carrier_rendered: false,
      card_state: "B",
      canonical_events_baseline: ["lookup_submitted", "card_rendered"],
    },
  },
  {
    fixture_id: "fx_pf_004_ordinary_control_table",
    raw_input: "what does table mean",
    normalized_input: "what does table mean",
    governing_term: "table",
    target_type: "wrapper_query",
    seed_class: "ordinary_control",
    expected: {
      route: "READ",
      phrase_mode_fired: true,
      lineage_rendered: false,
      carrier_rendered: false,
      card_state: "B",
      canonical_events_baseline: ["lookup_submitted", "card_rendered"],
    },
  },
];

export const WRAPPER_QUERY_FIXTURES: NarrowFixture[] = PROVING_FIXTURES.filter((fixture) =>
  fixture.fixture_id.startsWith("fx_wq_"),
);
